version: '3'

services:
  app:
    build: .
    container_name: engine
    ports:
      - ${APP_PORT}:80
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - ./docker/dev_php.ini:/etc/php5/apache2/php.ini
    restart: always
